CC := mpicc
FILE := bucket_sort_v
CFLAGS := -O3

all: $(FILE)1 $(FILE)2 $(FILE)3 $(FILE)4

$(FILE)1: $(FILE)1.c
	$(CC) -o $(FILE)1 $(FILE)1.c $(CFLAGS)
$(FILE)2: $(FILE)2.c
	$(CC) -o $(FILE)2 $(FILE)2.c $(CFLAGS)
$(FILE)3: $(FILE)3.c
	$(CC) -o $(FILE)3 $(FILE)3.c $(CFLAGS)
$(FILE)4: $(FILE)4.c
	$(CC) -o $(FILE)4 $(FILE)4.c $(CFLAGS)
