#!/bin/bash

flag1=$1
flag2=$2

module load GNU/6.2

make
out1=subsetResults
out2=codebreakerResults
rm -r ${out1}
echo ${flag1}

if [ "${flag1}"-eq"1" ];then
echo 'starting subset'
for j in 20 24 28
do
   for i in 1 2 3 4 5 6 7
   do
      ./subset.x ${j} ${i} >> ${out1}_${j}
   done
done

for j in 20 24 28
do 
   grep "Time" ${out1}_${j} | awk '{print $2 " " $3}' > data/subsetdata_${j}
done
fi

if["${flag2}"-ne"0" ];then
echo 'starting codebreak block'
rm -r ${out2}
cp ../codebreakerblock.c src/codebreaker/codebreaker.c
make

for i in 1 2 3 4 5
do
   mpirun -np ${i} ./codebreaker.x inp2.txt.ecp >> ${out2}
done

grep "Time" ${out2} | awk '{print $2 " " $4}' > data/codedata_block




echo 'starting codebreakercycle'
rm -r ${out2}
cp ../codebreakercycle.c src/codebreaker/codebreaker.c
make

for i in 1 2 3 4 5
do
   mpirun -np ${i} ./codebreaker.x inp2.txt.ecp >> ${out2}
done

grep "Time" ${out2} | awk '{print $2 " " $4}' > data/codedata_cycle


echo 'starting codebreak Bonus'
rm -r ${out2}
cp ../codebreakerbonus.c src/codebreaker/codebreaker.c
make

for i in 1 2 3 4 5
do
   mpirun -np ${i} ./codebreaker.x inp2.txt.ecp >> ${out2}
done

grep "Time" ${out2} | awk '{print $2 " " $4}' > data/codedata_bonus

fi


cd data

./GNUplotscript.gp
